name: e2e testing workflow

on:
  issue_comment:
    types: [created, edited]

jobs:
  e2e_testing:
    if: github.event.comment.body == 'Run e2e testing'
    strategy:
      max-parallel: 3
      matrix:
        node-version: [10.10.0, 10.10.0, 10.10.0]
    # container:
      # image: cypress/browsers:node11.13.0-chrome73
    runs-on: ubuntu-latest
    needs: deploy_to_aws
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Node version
        run: node -v

      - name: Show envs
        env:
          super_secret: ${{ secrets.DEVELOPMENT_TOKEN }}
          API_URL: https://example.com
        run: |
          echo $super_secret
          echo $API_URL
          echo $GITHUB_ACTION

      - uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn --no-progress --frozen-lockfile

      - name: test
        run: |
          yarn test:ci
          ls -al
        env:
          CI: true

      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage/
