name: Master branch

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
      - '**'

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
