name: Master branch

on:
  push:
    branches:
      - master
    tags-ignore:
      - '*'
      - '**'

jobs:
  bump_version:
    strategy:
      matrix:
        node-version: [10.10.0]
    runs-on: ubuntu-latest
    steps:
    - name: 'master pending'
      uses: 'deliverybot/deployment-status@v1'
      with:
        token: '${{ github.token }}'

    - uses: actions/checkout@v1

    - name: Build storybook
      run: |
        export CURRENT_HASH=$(echo $(git rev-parse --short HEAD))
        echo $CURRENT_HASH
        export COMMIT_MESSAGE="$(echo $(git log -n 1 --pretty=format:%B))"
        echo $COMMIT_MESSAGE
        export VERSION_TYPE="patch"
        export TAG=$(echo $(git tag --contains $CURRENT_HASH))
        echo $TAG
        # export VERSION_TYPE=$(node pipelines/get-version-type.js "$COMMIT_MESSAGE")
        if [ ! -z "$TAG" ] ; then exit 0; fi
        echo $VERSION_TYPE
        git --version
        git status
        # npm version $VERSION_TYPE -m "v%s"
        # git status
        # git push --follow-tags

    - name: 'master success'
      uses: 'deliverybot/deployment-status@v1'
      with:
        state: 'success'
        token: '${{ github.token }}'
