name: Master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    name: Unit testing

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: install dependencies
      run: yarn --no-progress --frozen-lockfile

    - name: test
      run: |
        yarn test
        ls -al
      env:
        CI: true

    - uses: actions/upload-artifact@master
      with:
        path: coverage/
