name: Master branch

on:
  push:
    branches:
      - master

jobs:
  storybook:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.10.0]

    steps:
    - uses: actions/checkout@v1
    - name: Build storybook
      run: echo 'Build storybook'

  unit_testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.10.0]

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Node version
      run: node -v

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Node version
      run: node -v

    - uses: actions/cache@preview
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: install dependencies
      run: yarn --no-progress --frozen-lockfile

    - name: test
      run: |
        yarn test
        ls -al
      env:
        CI: true

    - uses: actions/upload-artifact@master
      with:
        name: coverage
        path: coverage/

  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.10.0]

    steps:
    - uses: actions/checkout@v1
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
