name: Test-1 workflow

on:
  issue_comment:
    types: [created, edited]

jobs:
  storybook:
    if: github.event.comment.body == 'Deploy to test-1'
    strategy:
      matrix:
        node-version: [10.10.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build storybook
      run: echo 'Build storybook'

  unit_testing:
    if: github.event.comment.body == 'Deploy to test-1'
    strategy:
      matrix:
        node-version: [10.10.0]
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Node version
      run: node -v

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Node version
      run: node -v

    - uses: actions/cache@preview
      with:
        path: node_modules
        key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - uses: actions/cache@preview
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
        restore-keys: |
          ${{ runner.os }}-yarn-

    - name: install dependencies
      run: yarn --no-progress --frozen-lockfile

    - name: test
      run: |
        yarn test
        ls -al
      env:
        CI: true

    - uses: actions/upload-artifact@master
      with:
        name: coverage
        path: coverage/

  build:
    if: github.event.comment.body == 'Deploy to test-1'
    strategy:
      matrix:
        node-version: [10.10.0]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Test-1 env
      run: echo Test 1 env

  deploy_to_aws:
    strategy:
      matrix:
        node-version: [10.10.0]
    runs-on: ubuntu-latest
    needs: [storybook, unit_testing, build]
    steps:
    - name: Test-1 env
      run: echo Test 1 env
    - name: Run a one-line script
      run: echo 'Deploy to stage'

  e2e_testing:
    strategy:
      max-parallel: 3
      matrix:
        node-version: [10.10.0, 10.10.0, 10.10.0]
    runs-on: ubuntu-latest
    needs: deploy_to_aws
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Node version
        run: node -v

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Node version
        run: node -v

      - uses: actions/cache@preview
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - uses: actions/cache@preview
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: install dependencies
        run: yarn --no-progress --frozen-lockfile

      - name: test
        run: |
          yarn test:ci
          ls -al
        env:
          CI: true

      - uses: actions/upload-artifact@master
        with:
          name: coverage
          path: coverage/
